name: .NET
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Shutdown Ubuntu Mysql Service
      run: sudo service mysql stop
    - name: Start MariaDB
      uses: getong/mariadb-action@v1.1
      with:
        mysql root password: root
        mysql database: logbookDB
        mysql user: root
        mysql password: root
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
